```python
def spam(divideBy):
    x = 42 / divideBy
    return(x)


print(spam(2))
print(spam(12))
print(spam(0))
print(spam(1))
```

    21.0
    3.5
    


    ---------------------------------------------------------------------------

    ZeroDivisionError                         Traceback (most recent call last)

    <ipython-input-3-e5c7830528f2> in <module>
          6 print(spam(2))
          7 print(spam(12))
    ----> 8 print(spam(0))
          9 print(spam(1))
    

    <ipython-input-3-e5c7830528f2> in spam(divideBy)
          1 def spam(divideBy):
    ----> 2     x = 42 / divideBy
          3     return(x)
          4 
          5 
    

    ZeroDivisionError: division by zero


A **ZeroDivisionError** happens whenever you try to divide a number by zero. From the line number given in the error message, you know that the return statement in spam() is causing an error.

Errors can be handled with **try** and **except** statements. The code that could potentially have an error is put in a **try** clause. The program execution moves to the start of a following **except** clause if an error happens..


```python
def spam(divideBy):
    try:
        x = 42 / divideBy
        return(x)
    except ZeroDivisionError:
        print("Error: Invalid Argumnet!")
        
print(spam(2))
print(spam(5))
print(spam(0))
print(spam(4))
```

    21.0
    8.4
    Error: Invalid Argumnet!
    None
    10.5
    


```python
def spam(divideBy):
    x = 42 / divideBy
    return(x)
try:
    print(spam(2))
    print(spam(12))
    print(spam(0))
    print(spam(1))
except ZeroDivisionError:
    print('Error: Invalid argument.')
```

    21.0
    3.5
    Error: Invalid argument.
    


```python

```
